[package]
name = "pnetlink"
version = "0.1.0"
authors = ["root"]
build = "build.rs"

[build-dependencies.pnet_macros]
git = "https://github.com/polachok/libpnet"
branch = "le"
features = [ "with-syntex" ]

[dependencies.pnet_macros_support]
git = "https://github.com/polachok/libpnet"
branch = "le"

[dependencies.pnet]
git = "https://github.com/polachok/libpnet"
branch = "le"
features = [ "with-syntex" ]

[build-dependencies.syntex]
version = "0.42"

[dependencies]
libc = "0.2"

[dependencies]
rand = "0.3.14"
bitflags = "0.7"
byteorder = "0.5.3"
tokio-core = "0.1"
mio = "0.6"
